name: easy_quiz_game
description: Through this package, you can easily add quiz game in your apps.
version: 1.0.1
repository: https://github.com/nooralibutt/easy_quiz_game
homepage: https://github.com/nooralibutt/easy_quiz_game

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.2.3
  provider: ^6.0.5
  collection: ^1.17.0
  shared_preferences: ^2.0.17
  just_audio: ^0.9.31

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  assets:
    - assets/
    - assets/images/
    - assets/sounds/